//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDo
    {
        public int ID { get; set; }
        public string ToDoName { get; set; }
        public string ToDoDetails { get; set; }
        public Nullable<System.DateTime> ToDoDateTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
